---
- hosts: all
  gather_facts: False
  tasks:
  - name: "copy over rpm from my pc"
    copy:
      src: "/Users/sasha/Downloads/docker-ce-18.03.1.ce-1.el7.centos.x86_64.rpm"
      dest: /tmp/
  - name: "Install docker form rpm"
    yum:
      name: "/tmp/docker-ce-18.03.1.ce-1.el7.centos.x86_64.rpm"
      state: present