#---
#- hosts: all
#  roles:
#    - {role: '/Users/sasha/Desktop/work not for sync/git_projects/do-dpl/playbooks/roles/dynatrace'}
#  # - {role: 'apache', tags: 'apache'}

#ansible-playbook -i  ansible_inventory deploy_tmp.yml -e "cloud=nonprod" -b
---
- hosts: all
  roles:
    - {role: "/Users/sasha/Desktop/work_not_for_sync/git_projects/do-cmh/playbooks/roles/devmount"}
    - {role: '/Users/sasha/Desktop/work_not_for_sync/git_projects/do-cmh/playbooks/roles/os-basic'}
    - {role: '/Users/sasha/Desktop/work_not_for_sync/git_projects/do-cmh/playbooks/roles/users'}
    - {role: '/Users/sasha/Desktop/work_not_for_sync/git_projects/do-cmh/playbooks/roles/java'}
    - {role: '/Users/sasha/Desktop/work_not_for_sync/git_projects/do-cmh/playbooks/roles/s3sync'}
    - {role: '/Users/sasha/Desktop/work_not_for_sync/git_projects/do-cmh/playbooks/roles/tools'}